export const refs = {
  gallery: document.querySelector('.cocktails__list'),
  alphabet: document.querySelector('.hero__list'),
  searchForm: document.querySelector('.header__form'),
  list: document.querySelector('.hero__list'),
  cocktailList: document.querySelector('.cocktails__list'),
  overlay: document.querySelector('[data-overlay]'),
  btnOpenModal: document.querySelector('[data-modal-open]'),
  modal: document.querySelector('[data-modal]'),
  unscroll: document.querySelector('[data-unscroll]'),
  btnCloseModal: document.querySelector('[data-modal-close]'),
  qwerty: document.querySelector('.hero__datalist'),
  listFavCock: document.querySelector('.cocktails__list--favorite'),
  listFavIngr: document.querySelector('.cocktails__list--favIngr'),
  textFavPageCockt: document.querySelector('.text__favorite--cocktails'),
  textFavPageIngr: document.querySelector('.text__favorite--ingredients'),
  cockTitle: document.querySelector('h2.cocktails__title'),
  modalIngr: document.querySelector('[data-modal-ingredient]'),
  overlayIngr: document.querySelector('[data-overlay-ingredient]'),
};
